### ISSUE TITLE
set stripe_version 

### ISSUE THREAD

**Issue by habibun** [FLUX-SE/PayumStripeBundle#4]
Set specific version, which is discuss here

https://stripe.com/docs/api/versioning

```
$stripe = new \Stripe\StripeClient([
  "api_key" => "sk_test_your_key",
  "stripe_version" => "2020-08-27"
]);
```

is there any way i can set stripe version, thanks

**Comment by Prometee** [comment]
Hello @habibun,

Never tested it, but you can try to add this to your controller or to a Payum extension (onPreExecute) :

```php
use Stripe\Stripe;

Stripe::setApiVersion('2020-08-27);
```

**Comment by Prometee** [comment]
Here is an example (no tested yet):

```php
<?php

declare(strict_types=1);

namespace App\Payum\StripeCheckoutSession\Extension;

use FluxSE\PayumStripe\Action\Api\Resource\ResourceActionInterface;
use Payum\Core\Extension\ExtensionInterface;
use Stripe\Stripe;

final class SetStripeApiVersionExtension implements ExtensionInterface
{
    private string $apiVersion;

    public function __construct(string $apiVersion) {
        $this->apiVersion = $apiVersion;
    }

    public function onPreExecute(Context $context): void
    {
        $action = $context->getAction();
        // If it's not one of the Stripe API call
        if (false === $action instanceof ResourceActionInterface) {
            return;
        }
        
        Stripe::setApiVersion($this->apiVersion);
    }

    public function onExecute(Context $context): void
    {
    }

    public function onPostExecute(Context $context): void
    {
    }
}
```

```yaml
services:
    App\Payum\StripeCheckoutSession\Extension\SetStripeApiVersionExtension:
        public: true
        arguments:
            $apiVersion: '2020-08-27'
        tags:
            - name: payum.extension
              factory: stripe_checkout_session

```
